### ISSUE TITLE
Unable to create layer for relative Layout

### ISSUE THREAD

**Issue by Amolmbtb** [bhaveshjabuvani-credencys/CarouselEffect#2]
```
05-02 17:14:16.451 21084-21200/com.app.snehalniti W/OpenGLRenderer: Layer exceeds max. dimensions supported by the GPU (818x16777215, max=8192x8192)
05-02 17:14:16.451 21084-21200/com.app.snehalniti W/OpenGLRenderer: Layer exceeds max. dimensions supported by the GPU (818x16777215, max=8192x8192)
05-02 17:14:16.452 21084-21200/com.app.snehalniti W/OpenGLRenderer: Layer exceeds max. dimensions supported by the GPU (818x16777215, max=8192x8192)
05-02 17:14:16.452 21084-21200/com.app.snehalniti W/OpenGLRenderer: Layer exceeds max. dimensions supported by the GPU (818x16777215, max=8192x8192)
05-02 17:14:16.452 21084-21200/com.app.snehalniti W/OpenGLRenderer: Layer exceeds max. dimensions supported by the GPU (818x16777215, max=8192x8192)
05-02 17:14:16.453 21084-21084/com.app.snehalniti W/JNIHelp: Discarding pending exception (java.lang.IllegalStateException: Unable to create layer for RelativeLayout @9b858a0) to throw java/lang/IllegalStateException
05-02 17:14:16.453 21084-21084/com.app.snehalniti W/JNIHelp: Discarding pending exception (java.lang.IllegalStateException: Unable to create layer for RelativeLayout @35a5ecc) to throw java/lang/IllegalStateException
05-02 17:14:16.453 21084-21084/com.app.snehalniti W/JNIHelp: Discarding pending exception (java.lang.IllegalStateException: Unable to create layer for RelativeLayout @5349bb8) to throw java/lang/IllegalStateException
05-02 17:14:16.453 21084-21084/com.app.snehalniti W/JNIHelp: Discarding pending exception (java.lang.IllegalStateException: Unable to create layer for RelativeLayout @6960f7) to throw java/lang/IllegalStateException
05-02 17:14:20.460 21084-21084/com.app.snehalniti W/GAv4: syncDispatchLocalHits timed out: java.util.concurrent.TimeoutException
05-02 17:14:20.611 21084-21084/com.app.snehalniti E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.app.snehalniti, PID: 21084
                                                                    java.lang.IllegalStateException: Unable to create layer for RelativeLayout @d561a82
                                                                        at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                        at android.os.MessageQueue.next(MessageQueue.java:328)
                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5896)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

```

**Comment by bhaveshjabuvani88** [comment]
I think problem is with your layout.
Check out below link:

https://stackoverflow.com/questions/26626344/scene-transition-with-hero-elements-throws-layer-exceeds-max-dimensions-support
